---
title: མེ་ལོང་
email: tenzinmelhong@gmail.com
description: "ང་ནི་མེ་ལོང་གི་གཙོ་སྒྲིག་པ་ཡིན། བདག་གིས་མེ་ལོང་བརྒྱུད་ནས་བོད་མི་རྣམས་ཀྱི་མདུན་དུ་ཡིད་འགུག་ཅིང་སེམས་ཤུགས་འཕེལ་བ།\n
  བློ་སྐྱེད་ཐོབ་པ་བཅས་ཀྱི་ཁྱད་ཆོས་འཛོམས་པའི་བརྙན་ཐུང་ཁག་ཅིག་འཇོག་གི་ཡིན། \n བརྙན་ཐུང་འདི་དག་བརྒྱུད་ནས་བོད་མི་རྣམས་ཀྱིས་སོ་སོའི་ཉིན་རེའི་འཚོ་བའི་ནང་རང་གི་འཇིག་རྟེན་ལ་རན་པའི་ལྟ་ཚུལ་གསར་བ་དང་བློ་གྲོས་གསར་བ།\n
  ཐབས་ལམ་གསར་བ་སོགས་རྙེད་ཐུབ་པའི་རེ་བ་ཆེ། མེ་ལོང་གཙོ་སྒྲིག་པ་དཀོན་མཆོག་ནས།"
baseurl: ''
url: ''
github_username: melhong
paginate: 10
paginate_path: "/blog/page:num/"
markdown: kramdown
theme: minima
encoding: utf-8
plugins:
- jekyll-paginate
timezone: Etc/UTC
